using System.Diagnostics.CodeAnalysis;

namespace DBase.Tests.DBaseF5;

// ReSharper disable once UnusedMember.Global
public class DBaseF5 : DBaseTest<DBaseF5Record>;

[SuppressMessage("ReSharper", "InconsistentNaming", Justification = "Required for serialization")]
[SuppressMessage("ReSharper", "IdentifierTypo", Justification = "Required for serialization")]
public record DBaseF5Record(
    double? NF,
    string SEXE,
    string NOM,
    string COG1,
    string COG2,
    string TELEFON,
    string RENOM,
    double? NFP,
    double? NFM,
    string ARXN,
    DateTime? DATN,
    string LLON,
    string MUNN,
    string COMN,
    string PROV,
    string PAIN,
    string OFIC,
    string ARXB,
    DateTime? DATB,
    string LLOB,
    string MUNB,
    string COMB,
    string PAIB,
    string DRIB,
    string INAB,
    string OFTB,
    string OFNB,
    string AXC1,
    DateTime? DTC1,
    string LLC1,
    double? NFC1,
    string TCA1,
    string OTC1,
    string ONC1,
    string AXC2,
    DateTime? DTC2,
    string LLC2,
    double? NFC2,
    string TCA2,
    string OTC2,
    string ONC2,
    string AXC3,
    DateTime? DTC3,
    string LLC3,
    double? NFC3,
    string TCA3,
    string OTC3,
    string ONC3,
    string ARXD,
    DateTime? DATD,
    string LLOD,
    string OFTD,
    string OFND,
    string OBS1,
    string OBS2,
    string OBS3,
    string OBS4,
    string OBSE,
    string GHD);
